### ISSUE TITLE
variable country not found

### ISSUE THREAD

**Issue by megdalynn** [asjadnaqvi/stata-bumpline#2]
I tried running the package on my panel data with state/year observations.
both
- `bumpline gov_change cert_year, by(state) top(15) xsize(2) ysize(1)`
- `bumpline gov_change cert_year, by(state)`
produced error "`variable **country** not found`"

`rename state country`
`bumpline gov_change cert_year, by(country) top(15) xsize(2) ysize(1)`

works just fine.

**Comment by asjadnaqvi** [comment]
Patched! Can you reinstall and check again please.

**Comment by megdalynn** [comment]
Confirmed, works great! Thanks!
