### ISSUE TITLE
Twoway options to set marker line or fill color are not accepted

### ISSUE THREAD

**Issue by ericmelse** [asjadnaqvi/stata-bumpline#3]
Dear Asjad,

It appears that the Twoway options to set marker line color or marker fill color or marker line width are not accepted, like:
`bumpline total_ghg year, by(country) xsize(2) ysize(1) lw(1.2) msym(Sh) ms(2.3) mlc(black) mfc(white) mlw(*1.2) name(mfclw1sq, replace)`

But, I just noticed that when marker width is set as `mlwid(*2)` that then it is processed.
However, although this follows Stata being clever to 'understand' the abbreviation of the full title of this option, your code, I assume, should pass the documented abbreviation by `mlw(*2)` as well. Otherwise you can expect many users to start writing you about 'errors' they experience (like me).

**Comment by asjadnaqvi** [comment]
Please note that marker fill color is given by `mc()` and not `mfc()`. if `mc()` and `mlc()` are specified, they will overwrite the defaults.
