### ISSUE TITLE
Function returned error

### ISSUE THREAD

**Issue by sktanamas** [asjadnaqvi/stata-bumpline#9]
Good afternoon,
I'm running into an error when trying to use this package, even with your sample data and code. Below is the code in my do-file and the Stata error message it produces. I use Stata/SE 18.0.

Any suggestion for troubleshooting this would be greatly appreciated. And thank you for creating this useful package.

````
net install bumpline, from("https://raw.githubusercontent.com/asjadnaqvi/stata-bumpline/main/installation/") replace

ssc install palettes, replace
ssc install colrspace, replace

ssc install schemepack, replace
set scheme white_tableau 

use "https://github.com/asjadnaqvi/stata-bumpline/blob/main/data/owid_emissions_reduced.dta?raw=true", clear

drop if iso_code==""

// keep a random set of years
keep if inlist(year, 1990, 1992, 1995, 2000, 2005, 2007, 2010, 2013, 2016, 2019)

bumpline total_ghg year, by(country)
````

bumpline total_ghg year, by(country)
   ColrSpace::_recycle():  3021  class compiled at different times
    ColrSpace::Palette():     -  function returned error
    ColrSpace::palette():     -  function returned error
            getpalette():     -  function returned error
                 <istmt>:     -  function returned error
r(3021);

**Comment by sktanamas** [comment]
I restarted Stata and the issue no longer appears as long as I don't run the following code:
`set scheme white_tableau `

**Comment by asjadnaqvi** [comment]
looks like there is an error in the code where the colors are processed.
try updating colorpalette and colrspace and see if the error still persists:

```
ssc install palettes, replace
ssc install colrspace, replace
```
